name: Academia-Theme
version: 1.0.0

navigation:
  - title: Home
    url: /

defaults:
  - scope:
      path: ""
    values:
      layout: default

outline_thread: true

title: Site Title
description: Site Description
author: "Your name here"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .gitignore
  - LICENSE
  - README.md
  - CHANGELOG.md
  - screenshot.png
